import Provider from "@components/Provider";
import SessionWrapper from "@components/SessionWrapper";
import "@styles/scss/main.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "KEAM Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <SessionWrapper>{children}</SessionWrapper>
        </Provider>
      </body>
    </html>
  );
}
