import Provider from "@components/Provider";
import "@styles/scss/main.scss";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "A Glimpse to KEAM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Toaster
          position="bottom-center"
          reverseOrder={false}
          toastOptions={{
            duration: 3000,
          }}
        />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
