
import "@styles/scss/main.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "A Glimpse to KEAM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
