import Provider from "@components/Provider";
import SessionWrapper from "@components/SessionWrapper";
import "@styles/scss/main.scss";
import AdminHeader from "@widgets/admin/components/AdminHeader";
import AdminSidebar from "@widgets/admin/components/AdminSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "KEAM Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Provider>
        <SessionWrapper admin={true}>
          <div className="flex items-center flex-row w-screen">
            <AdminSidebar />
            <div className="flex flex-col w-full">
              <AdminHeader />
              <main className="min-h-[100vh] h-auto rounded-[5px] pt-[15vh] pl-[19vw] pr-[1vw] pb-[1vw] w-[99.5vw] flex  bg-red-50 bg-opacity-45">
                <div className="w-full h-[82vh] relative overflow-auto">{children}</div>
              </main>
            </div>
          </div>
        </SessionWrapper>
      </Provider>
    </div>
  );
}
